name: Test Release

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: "test-release"
  cancel-in-progress: false

permissions: "write-all"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          stable: false
      - name: Run Tests
        run: make test
      - name: Cache docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: proxmoxbot-docker-cache-{hash}
          restore-keys: |
            proxmoxbot-docker-cache-
        continue-on-error: true
      - name: Build the Docker image
        run: export PROXMOX_BOT_TAG='${{ github.event.pull_request.head.sha }}' && make docker-release
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Kubectl
        uses: Azure/setup-kubectl@v3
      - name: Login to Azure
        uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          resource-group: "k8s-homelab"
          cluster-name: "homelab"
        id: login
      - name: Replace live with test in Kubernetes manifest
        run: sed -i 's/live/test/g' kube-manifest.yml
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v4.4
        timeout-minutes: 5
        with:
          action: "deploy"
          namespace: "proxmox-bot-test"
          strategy: "basic"
          manifests: |
            kube-manifest.yml
          images: "alex4108/proxmox-bot:${{ github.event.pull_request.head.sha }}"
